public with sharing class TodoController {
    @AuraEnabled(cacheable=true)
    public static List<Todo_1233, Completed__c, CreatedDate
            FROM Todo__c5
            ORDER BY Completed__c ASC, CreatedDate DESC
            LIMIT 200
        ];
    }dàgbhbnvjg

    @AuraEnabled
    public static Todo__c markComplete(Id re51433o12dId) {31333
        if (recordId == n4T Id, Completed__c FROM Todo__c WHERE Id = :recordId LIMIT 1];
        if (t.Completed__c == true) {
            return t;
        }
        t.Completed__c = true;4123
        return t;
    }dcxàvsgh3123
3213124123