name: Salesforce Code Validation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Salesforce CLI
      run: npm install -g @salesforce/cli

    - name: Validate Project Structure
      run: |
        sf project validate --json
        sf project convert source --output-dir ./mdapi

    - name: Run Apex Linter
      run: |
        npm install -g pmd-bin
        pmd-bin run --dir force-app --rulesets category/apex/design.xml,category/apex/bestpractices.xml
