name: Lint and Build Check

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  lint-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Run LWC Lint
      run: npm run lint || true

    - name: Run Apex Static Analysis
      run: |
        npm install -g pmd-bin
        pmd-bin run pmd -d force-app/main/default/classes -R category/apex/design.xml
