name: Validate Salesforce Project

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Salesforce CLI
      run: npm install -g @salesforce/cli

    - name: Validate SFDX Project
      run: |
        sf project validate
        sf project deploy validate --source-dir force-app --ignore-errors
