name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    env:
      SFDX_AUTOUPDATE_DISABLE: true
      
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Salesforce CLI
      run: |
        npm install -g @salesforce/cli

    - name: Authenticate Dev Hub
      run: |
        sfdx force:auth:web:login -d -i ${{ secrets.CLIENT_ID }} -r ${{ secrets.DEV_HUB_USERNAME }}
      env:
        SF_AUTOUPDATE_DISABLE: true

    - name: Create Scratch Org
      id: scratchorg
      run: |
        sfdx force:org:create -f config/project-scratch-def.json -a scratch-org -d 1 -w 10 || exit 1
        echo "SCRATCH_ORG_ID=$(sfdx force:org:display --json | jq -r '.result.orgId')" >> $GITHUB_ENV
        echo "SCRATCH_ORG_URL=$(sfdx force:org:display --json | jq -r '.result.instanceUrl')" >> $GITHUB_ENV

    - name: Push Source to Scratch Org
      run: |
        sfdx force:source:push || exit 1

    - name: Run Apex Tests
      run: |
        sfdx force:apex:test:run -r human -w 10 || exit 1

    - name: Deploy to Production (if on main branch)
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Starting deployment to production org..."
        sfdx force:source:deploy -p force-app -u ${{ secrets.PROD_USERNAME }} || exit 1
        echo "Deployment to production org completed successfully."
      env:
        PROD_USERNAME: ${{ secrets.PROD_USERNAME }}

    - name: Clean Up Scratch Org
      if: always()
      run: |
        sfdx force:org:delete -o scratch-org -p
